name: .NET Core Desktop

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Build
    - name: Build
      run: dotnet publish -c Release

    - name: LS
      run: dir -Recurse

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/Release/net9.0/win-x64/publish/org-protocol-w32-handler.exe
